id = "wordbird"
name = "Wordbird"
version = "0.1.0"
schema_version = 1
authors = ["Till Hoffmann", "Thomas Walther"]
description = "Context bridge for Wordbird voice dictation. Makes Wordbird aware of the active Zed window and its respective WORDBIRD.md file when dictating."
repository = "https://github.com/tillahoffmann/wordbird"

[language_servers.wordbird-lsp]
languages = [
  "Bash",
  "C",
  "C#",
  "C++",
  "Clojure",
  "CSS",
  "Dart",
  "Dockerfile",
  "Elixir",
  "Elm",
  "Erlang",
  "Go",
  "Haskell",
  "HTML",
  "Java",
  "JavaScript",
  "JSON",
  "JSX",
  "Julia",
  "Kotlin",
  "LaTeX",
  "Lua",
  "Markdown",
  "OCaml",
  "PHP",
  "Plain Text",
  "Proto",
  "Python",
  "R",
  "Ruby",
  "Rust",
  "Scala",
  "Shell Script",
  "SQL",
  "Svelte",
  "Swift",
  "TOML",
  "TSX",
  "TypeScript",
  "Vue.js",
  "YAML",
  "Zig",
]
